name = "beplugged-invoicing"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "public", binding = "ASSETS" }

[[d1_databases]]
binding = "DB"
database_name = "invoicing"
database_id = "8863ff6e-e263-41e1-a3af-a229e776f81d"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.development]
vars = { ENVIRONMENT = "development" }
